str1 = "Bhanu is a Very GOOD BOY"
print("Given string(string)")
print(str1)
print("Unique elements: ")
print(unique(tolower(str1)))
nums = c(1, 2, 2, 3, 4, 4, 5, 6)
print("Given values(number)")
print(nums)
print("Unique values:")
print(unique(nums))
